name: Create Release and publish to ghcr

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # create release
      packages: write # upload to ghcr
    steps:
      - name: Get image name
        run: |
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}:$GITHUB_REF_NAME" >>${GITHUB_ENV}
      - 
        name: Checkout code
        uses: actions/checkout@master
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}
      -
        name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ github.token }} # This token is provided by Actions, you do not need to create your own token
        with:
          title: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}

